"""Add fields for finished slot notifications

Revision ID: 0c101b9d386d
Revises: 9a754af588ad
Create Date: 2025-11-17 10:51:50.818439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c101b9d386d'
down_revision: Union[str, Sequence[str], None] = '9a754af588ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add 'notify_finished' to 'user_tracked_slots'.
    # nullable=True allows this to be NULL, meaning "Inherit from User Global Default"
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_finished', sa.Boolean(), nullable=True))

    # 2. Add 'notify_finished_default' to 'users'.
    # server_default=sa.true() fills this column with TRUE for all existing users
    # nullable=False ensures it cannot be NULL in the future
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_finished_default', sa.Boolean(), server_default=sa.true(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_finished_default')

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('notify_finished')

    # ### end Alembic commands ###