"""add slot item counts table

Revision ID: 12b94b17380c
Revises: 68038cc7cbb1
Create Date: 2026-05-15 19:41:30.408473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b94b17380c'
down_revision: Union[str, Sequence[str], None] = '68038cc7cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_item_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['tracked_rooms.room_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'slot_id', 'item_id', name='_slot_item_count_uc')
    )
    
    # Backfill Data - JOIN with tracked_rooms to avoid orphaned data violating FK constraints
    op.execute("""
        INSERT INTO slot_item_counts (room_id, slot_id, item_id, count)
        SELECT ni.room_id, ni.receiving_slot_id, ni.item_id, COUNT(*)
        FROM notified_items ni
        JOIN tracked_rooms tr ON ni.room_id = tr.room_id
        GROUP BY ni.room_id, ni.receiving_slot_id, ni.item_id
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_item_counts')
    # ### end Alembic commands ###
