"""add fields for new features

Revision ID: 130cc583313b
Revises: 607741ad6b07
Create Date: 2025-12-29 07:00:47.024419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '130cc583313b'
down_revision: Union[str, Sequence[str], None] = '607741ad6b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combine_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suppress_own_events', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('combine_notifications_default', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('suppress_own_events_default', sa.Boolean(), nullable=False, server_default=sa.true()))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('suppress_own_events_default')
        batch_op.drop_column('combine_notifications_default')

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('suppress_own_events')
        batch_op.drop_column('combine_notifications')

    # ### end Alembic commands ###
