"""Add item_flags to NotifiedItem

Revision ID: 17099a792d8b
Revises: 9a45238cb786
Create Date: 2025-11-05 21:37:24.124028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17099a792d8b'
down_revision: Union[str, Sequence[str], None] = '9a45238cb786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_flags', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.drop_column('item_flags')

    # ### end Alembic commands ###
