"""add suppress_connected column

Revision ID: 182848ed7572
Revises: 9b2b25ffd762
Create Date: 2026-03-03 09:04:53.681355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182848ed7572'
down_revision: Union[str, Sequence[str], None] = '9b2b25ffd762'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('suppress_connected', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('suppress_connected')

    # ### end Alembic commands ###
