"""add new security fields

Revision ID: 19d6add4ee1e
Revises: 7cf0fa8c221d
Create Date: 2025-11-09 17:15:39.261982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d6add4ee1e'
down_revision: Union[str, Sequence[str], None] = '7cf0fa8c221d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_blocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jwt_blocklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jwt_blocklist_jti'), ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jwt_blocklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jwt_blocklist_jti'))

    op.drop_table('jwt_blocklist')
    # ### end Alembic commands ###
