"""Add last_remote_activity for TrackedRoom

Revision ID: 2a96c4d3bd18
Revises: 97763127e09f
Create Date: 2026-02-02 20:34:12.995266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a96c4d3bd18'
down_revision: Union[str, Sequence[str], None] = '97763127e09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_remote_activity', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.drop_column('last_remote_activity')

    # ### end Alembic commands ###
