"""add cached cheese columns

Revision ID: 2ca7b0ce4bb1
Revises: 0c101b9d386d
Create Date: 2025-11-19 05:57:27.735339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca7b0ce4bb1'
down_revision: Union[str, Sequence[str], None] = '0c101b9d386d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cached_cheese_json', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cheese_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.drop_column('cheese_updated_at')
        batch_op.drop_column('cached_cheese_json')

    # ### end Alembic commands ###
