"""Update notify_finished column

Revision ID: 404c01a19ea1
Revises: 0c101b9d386d
Create Date: 2025-11-17 13:42:22.397579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404c01a19ea1'
down_revision: Union[str, Sequence[str], None] = '0c101b9d386d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.alter_column('notify_finished',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.alter_column('notify_finished',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
