"""Add backfill boolean to usertrackedslots

Revision ID: 5227efd04445
Revises: 8a3ab05cc5c8
Create Date: 2025-11-07 16:37:23.428712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5227efd04445'
down_revision: Union[str, Sequence[str], None] = '8a3ab05cc5c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        # --- ADD server_default='true' right here ---
        batch_op.add_column(sa.Column('needs_backfill', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('needs_backfill')

    # ### end Alembic commands ###
