"""Add ui_show_useful_default to User

Revision ID: 5427fbf85337
Revises: 87487ef32292
Create Date: 2026-05-17 10:45:24.636254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5427fbf85337'
down_revision: Union[str, Sequence[str], None] = '87487ef32292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_show_useful_default', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ui_show_useful_default')

    # ### end Alembic commands ###
