"""add fields for condensed notification options

Revision ID: 5c2e69a88f8f
Revises: e1cd1fd40b21
Create Date: 2025-11-24 06:33:48.113971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2e69a88f8f'
down_revision: Union[str, Sequence[str], None] = 'e1cd1fd40b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_condensed_messages', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_condensed_messages_default', sa.Boolean(), nullable=False, server_default=sa.false()))


    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('use_condensed_messages_default')

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('use_condensed_messages')

    # ### end Alembic commands ###
