"""add notifiy_hints_remote_items_default

Revision ID: 619cd95819b6
Revises: b6bc740dccb8
Create Date: 2025-11-20 15:08:03.918401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619cd95819b6'
down_revision: Union[str, Sequence[str], None] = 'b6bc740dccb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_hints_remote_items_default', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_hints_remote_items_default')

    # ### end Alembic commands ###
