"""make fcm_token unique

Revision ID: 66897cf311d5
Revises: 3173716ea9d7
Create Date: 2025-12-18 09:48:14.114016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66897cf311d5'
down_revision: Union[str, Sequence[str], None] = '3173716ea9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_fcm_token'))
        batch_op.create_unique_constraint('uq_devices_fcm_token', ['fcm_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_devices_fcm_token'), ['fcm_token'], unique=False)

    # ### end Alembic commands ###
