"""allow_multiple_item_thresholds

Revision ID: 68038cc7cbb1
Revises: e62cbad2759c
Create Date: 2026-05-14 15:28:45.661034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68038cc7cbb1'
down_revision: Union[str, Sequence[str], None] = 'e62cbad2759c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_item_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tracked_slot_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_tracked_slot_id'], ['user_tracked_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tracked_slot_id', 'item_name', 'threshold', name='_slot_item_threshold_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_item_thresholds')
    # ### end Alembic commands ###
