"""add_platform_to_devices

Revision ID: 6aa084c2474f
Revises: fdb86a1c81bc
Create Date: 2026-06-15 12:40:28.998930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aa084c2474f'
down_revision: Union[str, Sequence[str], None] = 'fdb86a1c81bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.String(), server_default='android', nullable=False))
        batch_op.drop_constraint(batch_op.f('_user_android_id_uc'), type_='unique')
        batch_op.create_unique_constraint('_user_android_id_uc', ['user_id', 'android_id', 'platform'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_constraint('_user_android_id_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('_user_android_id_uc'), ['user_id', 'android_id'])
        batch_op.drop_column('platform')

    # ### end Alembic commands ###
