"""Change datapackage entity_id to BigInteger

Revision ID: 72036ef42ba1
Revises: 783b23da75cc
Create Date: 2025-10-31 14:09:08.308020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72036ef42ba1'
down_revision: Union[str, Sequence[str], None] = '783b23da75cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datapackage_cache', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_fcm_token'), ['fcm_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_fcm_token'))

    with op.batch_alter_table('datapackage_cache', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
