"""add_is_group_to_user_ignore_items

Revision ID: 748c071d0d33
Revises: a7abd175f0e5
Create Date: 2026-06-08 15:35:16.507085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748c071d0d33'
down_revision: Union[str, Sequence[str], None] = 'a7abd175f0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ignore_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_group', sa.Boolean(), server_default='f', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ignore_items', schema=None) as batch_op:
        batch_op.drop_column('is_group')

    # ### end Alembic commands ###
