"""Add android_id to device table

Revision ID: 783b23da75cc
Revises: febac406a8a7
Create Date: 2025-10-31 10:55:39.183884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783b23da75cc'
down_revision: Union[str, Sequence[str], None] = 'febac406a8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        # 1. Add the new android_id column
        batch_op.add_column(sa.Column('android_id', sa.String(), nullable=True))
        
        # 2. Create an index for it
        batch_op.create_index(batch_op.f('ix_devices_android_id'), ['android_id'], unique=False)
        
        # 3. Drop the old unique constraint/index on fcm_token
        # Note: We assume the old constraint was named 'ix_devices_fcm_token'
        # If autogenerate gave a different name, use that.
        batch_op.drop_index(batch_op.f('ix_devices_fcm_token'))
        
        # 4. Create the new unique constraint
        batch_op.create_unique_constraint('_user_android_id_uc', ['user_id', 'android_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        # 1. Drop the new unique constraint
        batch_op.drop_constraint('_user_android_id_uc', type_='unique')
        
        # 2. Re-create the old unique index/constraint on fcm_token
        batch_op.create_index(batch_op.f('ix_devices_fcm_token'), ['fcm_token'], unique=True)
        
        # 3. Drop the android_id index
        batch_op.drop_index(batch_op.f('ix_devices_android_id'))
        
        # 4. Drop the android_id column
        batch_op.drop_column('android_id')

    # ### end Alembic commands ###
