"""Add performance indexes for history and cache

Revision ID: 7cf0fa8c221d
Revises: 5227efd04445
Create Date: 2025-11-07 18:01:49.229191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf0fa8c221d'
down_revision: Union[str, Sequence[str], None] = '5227efd04445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.create_index('ix_notifiedhint_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.create_index('ix_notifieditem_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.drop_index('ix_notifieditem_timestamp')

    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.drop_index('ix_notifiedhint_timestamp')

    # ### end Alembic commands ###
