"""Add ui_show_progression_default to User

Revision ID: 87487ef32292
Revises: 68038cc7cbb1
Create Date: 2026-05-15 18:25:05.778957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87487ef32292'
down_revision: Union[str, Sequence[str], None] = '68038cc7cbb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_show_progression_default', sa.Boolean(), nullable=False, server_default='t'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ui_show_progression_default')

    # ### end Alembic commands ###
