"""Add cheese sync lock fields to user

Revision ID: 8a3ab05cc5c8
Revises: 0e272bba8b1c
Create Date: 2025-11-07 15:03:54.749235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a3ab05cc5c8'
down_revision: Union[str, Sequence[str], None] = '0e272bba8b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_syncing_cheese', sa.Boolean(), server_default='f', nullable=False))
        batch_op.add_column(sa.Column('cheese_sync_started_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cheese_sync_started_at')
        batch_op.drop_column('is_syncing_cheese')

    # ### end Alembic commands ###
