"""Add/Change fields for Guest Mode

Revision ID: 9a754af588ad
Revises: 19d6add4ee1e
Create Date: 2025-11-14 10:17:14.727130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a754af588ad'
down_revision: Union[str, Sequence[str], None] = '19d6add4ee1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_guest', sa.Boolean(), server_default='t', nullable=False))
        batch_op.add_column(sa.Column('guest_uuid', sa.String(), nullable=True))
        batch_op.alter_column('discord_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('discord_username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_guest_uuid'), ['guest_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_guest_uuid'))
        batch_op.alter_column('discord_username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('discord_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('guest_uuid')
        batch_op.drop_column('is_guest')

    # ### end Alembic commands ###
