"""Create initial production schema

Revision ID: 9e4507087e14
Revises: 
Create Date: 2025-10-31 18:14:14.887128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4507087e14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datapackage_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game', 'checksum', 'entity_type', 'entity_id', name='_game_checksum_entity_uc')
    )
    with op.batch_alter_table('datapackage_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datapackage_cache_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_datapackage_cache_game'), ['game'], unique=False)

    op.create_table('notified_hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('item_owner_id', sa.Integer(), nullable=False),
    sa.Column('location_owner_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_found', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'item_id', 'location_id', 'item_owner_id', 'location_owner_id', name='_hint_event_uc')
    )
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notified_hints_room_id'), ['room_id'], unique=False)

    op.create_table('notified_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('receiving_slot_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'receiving_slot_id', 'item_id', 'location_id', name='_item_event_uc')
    )
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notified_items_room_id'), ['room_id'], unique=False)

    op.create_table('tracked_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('tracker_id', sa.String(), nullable=True),
    sa.Column('game_checksums_json', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('last_successful_poll', sa.DateTime(), nullable=True),
    sa.Column('failed_poll_count', sa.Integer(), nullable=False),
    sa.Column('cached_full_address', sa.String(), nullable=True),
    sa.Column('cached_total_slots', sa.Integer(), nullable=True),
    sa.Column('last_api_check', sa.DateTime(), nullable=True),
    sa.Column('cached_players_json', sa.String(), nullable=True),
    sa.Column('is_setup', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracked_rooms_room_id'), ['room_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=False),
    sa.Column('discord_username', sa.String(), nullable=False),
    sa.Column('discord_avatar_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notify_progression_default', sa.Boolean(), nullable=False),
    sa.Column('notify_useful_default', sa.Boolean(), nullable=False),
    sa.Column('notify_hints_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_discord_id'), ['discord_id'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('android_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'android_id', name='_user_android_id_uc')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_android_id'), ['android_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_fcm_token'), ['fcm_token'], unique=False)

    op.create_table('user_room_subscriptions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('icon_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['tracked_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'room_id')
    )
    op.create_table('user_tracked_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('notify_progression', sa.Boolean(), nullable=True),
    sa.Column('notify_useful', sa.Boolean(), nullable=True),
    sa.Column('notify_hints', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['tracked_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id', 'room_id'], ['user_room_subscriptions.user_id', 'user_room_subscriptions.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'room_id', 'slot_id', name='_user_room_slot_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tracked_slots')
    op.drop_table('user_room_subscriptions')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_fcm_token'))
        batch_op.drop_index(batch_op.f('ix_devices_android_id'))

    op.drop_table('devices')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_discord_id'))

    op.drop_table('users')
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracked_rooms_room_id'))

    op.drop_table('tracked_rooms')
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notified_items_room_id'))

    op.drop_table('notified_items')
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notified_hints_room_id'))

    op.drop_table('notified_hints')
    with op.batch_alter_table('datapackage_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datapackage_cache_game'))
        batch_op.drop_index(batch_op.f('ix_datapackage_cache_checksum'))

    op.drop_table('datapackage_cache')
    # ### end Alembic commands ###
