"""Add timestamp and is_found to NotifiedHint

Revision ID: a912652242ab
Revises: 245b7fe8d706
Create Date: 2025-10-27 22:15:23.026751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision: str = 'a912652242ab'
down_revision: Union[str, Sequence[str], None] = '245b7fe8d706'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted for SQLite NOT NULL ###
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(),
                                      nullable=False,
                                      server_default=func.now())) # <-- Use func.now() for server default
        batch_op.add_column(sa.Column('is_found', sa.Boolean(),
                                      nullable=False,
                                      server_default=text('0'))) # <-- Use text('0') for SQLite boolean default
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notified_hints', 'is_found')
    op.drop_column('notified_hints', 'timestamp')
    # ### end Alembic commands ###
