"""add_filler_trap_prefs

Revision ID: a971160f9c05
Revises: d6392bd7f181
Create Date: 2026-07-09 21:20:57.757676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a971160f9c05'
down_revision: Union[str, Sequence[str], None] = 'd6392bd7f181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_filler_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('notify_trap_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ui_show_filler_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('ui_show_trap_default', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_filler', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_trap', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ui_show_trap_default')
        batch_op.drop_column('ui_show_filler_default')
        batch_op.drop_column('notify_trap_default')
        batch_op.drop_column('notify_filler_default')

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('notify_trap')
        batch_op.drop_column('notify_filler')

    # ### end Alembic commands ###
