"""add field for hint item classification

Revision ID: bb356718b137
Revises: 5c2e69a88f8f
Create Date: 2025-12-01 05:59:59.727813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb356718b137'
down_revision: Union[str, Sequence[str], None] = '5c2e69a88f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_flags', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_hints', schema=None) as batch_op:
        batch_op.drop_column('item_flags')

    # ### end Alembic commands ###
