"""replace_slot_item_threshold_with_threshold_groups

Revision ID: d6392bd7f181
Revises: fdb86a1c81bc
Create Date: 2026-06-18 06:31:50.554870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6392bd7f181'
down_revision: Union[str, Sequence[str], None] = 'fdb86a1c81bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threshold_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tracked_slot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_triggered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_tracked_slot_id'], ['user_tracked_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('threshold_group_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['threshold_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Data migration: Migrate existing single-item thresholds into the new group tables
    connection = op.get_bind()
    try:
        old_rows = connection.execute(sa.text(
            "SELECT id, user_tracked_slot_id, item_name, threshold FROM slot_item_thresholds"
        )).fetchall()
    except Exception:
        old_rows = []

    if old_rows:
        threshold_groups_tbl = sa.table(
            'threshold_groups',
            sa.column('id', sa.Integer),
            sa.column('user_tracked_slot_id', sa.Integer),
            sa.column('name', sa.String),
            sa.column('is_triggered', sa.Boolean)
        )
        threshold_group_items_tbl = sa.table(
            'threshold_group_items',
            sa.column('group_id', sa.Integer),
            sa.column('item_name', sa.String),
            sa.column('quantity', sa.Integer),
            sa.column('is_group', sa.Boolean)
        )
        
        for old_id, slot_db_id, item_name, threshold_count in old_rows:
            group_name = item_name.strip()
            result = connection.execute(
                threshold_groups_tbl.insert().values(
                    user_tracked_slot_id=slot_db_id,
                    name=group_name,
                    is_triggered=False
                )
            )
            group_id = result.inserted_primary_key[0]
            
            connection.execute(
                threshold_group_items_tbl.insert().values(
                    group_id=group_id,
                    item_name=item_name.strip(),
                    quantity=threshold_count,
                    is_group=False
                )
            )

    op.drop_table('slot_item_thresholds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_item_thresholds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_tracked_slot_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('threshold', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_tracked_slot_id'], ['user_tracked_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tracked_slot_id', 'item_name', 'threshold', name=op.f('_slot_item_threshold_uc'))
    )
    op.drop_table('threshold_group_items')
    op.drop_table('threshold_groups')
    # ### end Alembic commands ###
