"""add notifiy_hints_remote_items to UserTrackedSlot

Revision ID: e1cd1fd40b21
Revises: 619cd95819b6
Create Date: 2025-11-21 10:39:29.077261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cd1fd40b21'
down_revision: Union[str, Sequence[str], None] = '619cd95819b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_hints_remote_items', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('notify_hints_remote_items')

    # ### end Alembic commands ###
