"""updates to allow full history fields for the app

Revision ID: eb68af7f2a99
Revises: e8a739c12610
Create Date: 2025-11-19 14:33:09.739605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb68af7f2a99'
down_revision: Union[str, Sequence[str], None] = 'e8a739c12610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sending_slot_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notified_items', schema=None) as batch_op:
        batch_op.drop_column('sending_slot_id')

    # ### end Alembic commands ###
