"""add fields for history screen ui toggle preferences

Revision ID: ed960a254a42
Revises: bb356718b137
Create Date: 2025-12-01 06:13:20.730809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed960a254a42'
down_revision: Union[str, Sequence[str], None] = 'bb356718b137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_show_finished_default', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('ui_show_found_hints_default', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ui_show_found_hints_default')
        batch_op.drop_column('ui_show_finished_default')

    # ### end Alembic commands ###
