"""add snooze columns

Revision ID: fc573f17b4d6
Revises: 97763127e09f
Create Date: 2026-01-11 13:43:45.788845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc573f17b4d6'
down_revision: Union[str, Sequence[str], None] = '97763127e09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snooze_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('snooze_wake_on_slot_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('global_snooze_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('global_snooze_until')

    with op.batch_alter_table('user_tracked_slots', schema=None) as batch_op:
        batch_op.drop_column('snooze_wake_on_slot_id')
        batch_op.drop_column('snooze_until')

    # ### end Alembic commands ###
