"""add_revive_attempt_and_immediate_poll

Revision ID: fdb86a1c81bc
Revises: 748c071d0d33
Create Date: 2026-06-12 08:58:30.705195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb86a1c81bc'
down_revision: Union[str, Sequence[str], None] = '748c071d0d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_revive_attempt', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('needs_immediate_poll', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracked_rooms', schema=None) as batch_op:
        batch_op.drop_column('needs_immediate_poll')
        batch_op.drop_column('last_revive_attempt')

    # ### end Alembic commands ###
