package com.jones.aptracker.ui

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.jones.aptracker.BuildConfig // This is auto-generated by Gradle
import com.jones.aptracker.network.RetrofitClient
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

// This sealed class defines the "state" of the app on launch
sealed class AppVersionState {
    object Checking : AppVersionState()
    object UpToDate : AppVersionState()
    data class Outdated(val storeUrl: String) : AppVersionState()
    data class Error(val message: String) : AppVersionState()
}

class MainViewModel(application: Application) : AndroidViewModel(application) {

    private val _versionState = MutableStateFlow<AppVersionState>(AppVersionState.Checking)
    val versionState = _versionState.asStateFlow()

    private val apiService = RetrofitClient.instance

    init {
        checkAppVersion()
    }

    fun checkAppVersion() {
        _versionState.value = AppVersionState.Checking
        viewModelScope.launch {
            try {
                // 1. Get the minimum version from the server
                val config = apiService.getConfig()
                val minVersion = config.min_app_version

                // 2. Get this app's current version
                val currentVersion = BuildConfig.VERSION_CODE

                // 3. Compare
                if (currentVersion >= minVersion) {
                    _versionState.value = AppVersionState.UpToDate
                } else {
                    // This app is old. Show the "Outdated" state
                    // We can pass any URL, but your GitHub one is good.
                    _versionState.value = AppVersionState.Outdated("https://github.com/wrjones104/ap-tracker/releases")
                }

            } catch (e: Exception) {
                // Handle network errors, etc.
                // For UAT, let's allow the app to load if the check fails.
                // In production, you might want a stricter AppVersionState.Error
                _versionState.value = AppVersionState.Error("Failed to check for updates: ${e.message}. Allowing app to load.")
                // _versionState.value = AppVersionState.UpToDate // Failsafe: Let them in if the check fails
            }
        }
    }
}